"add t2, %[m], x0                               \n\t"
"addi %[add_cnt], %[add_cnt], 1                 \n\t"
"reverse_loop:                                  \n\t"
    "slli %[b], %[b], 1                         \n\t" 
    "andi t1, t2, 1                             \n\t"
    "or %[b], %[b], t1                          \n\t"
    "srli t2, t2, 1                             \n\t"
    "addi %[others_cnt], %[others_cnt], 5       \n\t"
    "bnez t2, reverse_loop                      \n\t"
