"add t2, %[m], x0                               \n\t"
"addi t0, x0, 0                                 \n\t"
"addi %[add_cnt], %[add_cnt], 2                 \n\t"
"reverse_loop:                                  \n\t"
    "slli t0, t0, 1                             \n\t"
    "andi t1, %[b], 1                           \n\t"
    "or t0, t0, t1                              \n\t"
    "srli %[b], %[b], 1                         \n\t"
    "addi t2, t2, -1                            \n\t"
    "addi %[add_cnt], %[add_cnt], 1             \n\t"
    "addi %[others_cnt], %[others_cnt], 5       \n\t"
    "bnez t2, reverse_loop                      \n\t"
"add %[b], t0, x0                               \n\t"
"addi %[add_cnt], %[add_cnt], 1                 \n\t"

