"log_loop:                                 \n\t"
    "srli %[N], %[N], 1                    \n\t"
    "addi %[log], %[log], 1                \n\t"
    "addi %[add_cnt], %[add_cnt], 1        \n\t"
    "addi %[others_cnt], %[others_cnt], 2  \n\t"
    "bnez %[N], log_loop                   \n\t"
